---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: my-secret-individual
  namespace: config-demo
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: my-secret-individual
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.myindivsecretsecret.key }}
      property: foo
